version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

    # limiting the pull request
