env:
    es2022: true
    mongo: true

parserOptions:
    ecmaVersion: 2022
    sourceType: "module"

extends: "eslint:recommended"
rules:
    no-prototype-builtins: 0
    no-useless-escape: 0
    no-irregular-whitespace: 0
    no-inner-declarations: 0
    no-unused-vars: [0, {"varsIgnorePattern": "^_", "args": "none"}]
    no-empty: 0
    no-redeclare: 0
    no-constant-condition: 0
    no-loss-of-precision: 0
