version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
# this is for checking for package update weekly
